name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - uses: actions/upload-artifact@v2
      name: Upload Artifacts
      with:
        name: dotnetcore-artifact
        path: bin/Release/net5.0/Eight.dll
    - name: Test
      run: dotnet test --no-restore --verbosity normal
